# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [6]:
# Your code here
import numpy as np
import random

A = np.array([[1, 3], [4, 6], [7, 9]])
B = np.array([[2], [4]])
C = np.array([[1], [5]])

LHS = A.dot(B+C)
RHS = (A.dot(B) + A.dot(C))
print(LHS == RHS)

[[ True]
 [ True]
 [ True]]


## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [7]:
# Your code here 
A = np.array([[1, 3, 5], [2, 4, 6]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C = np.array([[2, 4], [6, 8], [10, 12]])

LHS = A.dot(B.dot(C))
RHS = (A.dot(B)).dot(C)

print(LHS == RHS)

[[ True  True]
 [ True  True]]


## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [13]:
# Your code here 
A = np.array([[1, 2], [4, 5]])
B = np.array([[2, 4], [5, 7]])

LHS = A.dot(B)
RHS = B.dot(A)

print(LHS)
print(RHS)

LHS == RHS

[[12 18]
 [33 51]]
[[18 24]
 [33 45]]


array([[False, False],
       [ True, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [15]:
# Your code here 
x = np.array([[3], [4], [5]])
y = np.array([[6], [7], [8]])

LHS = np.transpose(x).dot(y)
RHS = np.transpose(y).dot(x)

print(LHS == RHS)

[[ True]]


## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [16]:
# Your code here 
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])

LHS = np.transpose(A.dot(B))
RHS = np.transpose(B).dot(np.transpose(A))

print(LHS == RHS)

[[ True  True]
 [ True  True]]


## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 